name: Polygon Integration Tests

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize

jobs:
  check_flags:
    name: Check flags
    runs-on: ubuntu-latest
    outputs:
      message: ${{ steps.get_commit_message.outputs.headCommitMsg }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Print head git commit message
        id: get_commit_message
        run: echo "::set-output name=headCommitMsg::$(git show -s --format=%s)"

  polygon-integration1:
    name: PIT 1 - Balancer
    runs-on: ubuntu-latest
    needs: check_flags
    if: ${{ contains(needs.check_flags.outputs.message, '[run-integration]') || contains(needs.check_flags.outputs.message, '[run-polygon]') }}
    env:
      POLYGON_URL: ${{ secrets.POLYGON_ALCHEMY_URL_INTEGRATION_TEST }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Hit node_modules cache
        uses: actions/cache@v3
        id: node-cache
        with:
          path: "**/node_modules"
          key: npm-v2-${{ hashFiles('**/package-lock.json') }}
          restore-keys: npm-v2-
      - name: Install dependencies
        run: npm ci
        if: steps.node-cache.outputs.cache-hit != 'true'
      - name: Run Polygon fork in background
        run: |
          npx hardhat node --config hardhat.config-compile.ts --fork $POLYGON_URL &
      - name: Hardhat compile TypeChain
        run: npx hardhat --config hardhat.config-compile.ts typechain
      - name: Hardhat compile
        run: npx hardhat compile

      - name: BalancerComposableStablePoolAggregatorTest
        if: always()
        run: |
          npx hardhat test ./test/integration/polygon/balancerV2/BalancerComposableStablePoolAggregatorTest.ts --network localhost

      - name: BalancerRewardsTest
        if: always()
        run: |
          npx hardhat test ./test/integration/polygon/balancerV2/BalancerRewardsTest.ts --network localhost

      - name: BalancerStablePoolAggregatorTest
        if: always()
        run: |
          npx hardhat test ./test/integration/polygon/balancerV2/BalancerStablePoolAggregatorTest.ts --network localhost

      - name: BalancerTest
        if: always()
        run: |
          npx hardhat test ./test/integration/polygon/balancerV2/BalancerTest.ts --network localhost

      - name: Balancer V2 Staking (Asset Guard)
        if: always()
        run: |
          npx hardhat test ./test/integration/polygon/balancerV2/BalancerV2GaugeAssetGuardTest.ts --network localhost

      - name: Balancer V2 Staking (Contract Guard)
        if: always()
        run: |
          npx hardhat test ./test/integration/polygon/balancerV2/BalancerV2GaugeContractGuardTest.ts --network localhost

  polygon-integration2:
    name: PIT 2
    runs-on: ubuntu-latest
    needs: check_flags
    if: ${{ contains(needs.check_flags.outputs.message, '[run-integration]') || contains(needs.check_flags.outputs.message, '[run-polygon]') }}
    env:
      POLYGON_URL: ${{ secrets.POLYGON_ALCHEMY_URL_INTEGRATION_TEST }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Hit node_modules cache
        uses: actions/cache@v3
        id: node-cache
        with:
          path: "**/node_modules"
          key: npm-v2-${{ hashFiles('**/package-lock.json') }}
          restore-keys: npm-v2-
      - name: Install dependencies
        run: npm ci
        if: steps.node-cache.outputs.cache-hit != 'true'
      - name: Run Polygon fork in background
        run: |
          npx hardhat node --config hardhat.config-compile.ts --fork $POLYGON_URL &
      - name: Hardhat compile TypeChain
        run: npx hardhat --config hardhat.config-compile.ts typechain
      - name: Hardhat compile
        run: npx hardhat compile

      - name: OneInchTest
        if: always()
        run: |
          npx hardhat test ./test/integration/polygon/OneInchTest.ts --network localhost

      - name: ArrakisTest
        if: always()
        run: |
          npx hardhat test ./test/integration/polygon/arrakis/*.ts --network localhost

      - name: UniswapV3NonfungiblePositionGuardTest
        if: always()
        run: |
          npx hardhat test ./test/integration/polygon/uniswapV3/UniswapV3NonfungiblePositionGuardTest.ts --network localhost

      - name: UniswapV3AssetGuardTest
        if: always()
        run: |
          npx hardhat test ./test/integration/polygon/uniswapV3/UniswapV3AssetGuardTest.ts --network localhost

      - name: UniswapV3PriceLibraryTest
        if: always()
        run: |
          npx hardhat test ./test/integration/polygon/uniswapV3/UniswapV3PriceLibraryTest.ts --network localhost

      - name: UniswapV3SwapRouterGuardTest
        if: always()
        run: |
          npx hardhat test ./test/integration/polygon/uniswapV3/UniswapV3SwapRouterGuardTest.ts --network localhost

      - name: ZeroExSwapsTest
        if: always()
        run: |
          npx hardhat test ./test/integration/polygon/zeroEx/ZeroExSwapsTest.ts --network localhost

  polygon-integration3:
    name: PIT 3 - Aave
    runs-on: ubuntu-latest
    needs: check_flags
    if: ${{ contains(needs.check_flags.outputs.message, '[run-integration]') || contains(needs.check_flags.outputs.message, '[run-polygon]') }}
    env:
      POLYGON_URL: ${{ secrets.POLYGON_ALCHEMY_URL_INTEGRATION_TEST }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Hit node_modules cache
        uses: actions/cache@v3
        id: node-cache
        with:
          path: "**/node_modules"
          key: npm-v2-${{ hashFiles('**/package-lock.json') }}
          restore-keys: npm-v2-
      - name: Install dependencies
        run: npm ci
        if: steps.node-cache.outputs.cache-hit != 'true'
      - name: Run Polygon fork in background
        run: |
          npx hardhat node --config hardhat.config-compile.ts --fork $POLYGON_URL &
      - name: Hardhat compile TypeChain
        run: npx hardhat --config hardhat.config-compile.ts typechain
      - name: Hardhat compile
        run: npx hardhat compile

      - name: LendingEnabledAssetGuardTest
        if: always()
        run: |
          npx hardhat test ./test/integration/polygon/aave/LendingEnabledAssetGuardTest.ts --network localhost

      - name: AaveV2Test
        if: always()
        run: |
          npx hardhat test ./test/integration/polygon/aave/AaveV2Test.ts --network localhost

      - name: AaveV2TestWithWETH
        if: always()
        run: |
          npx hardhat test ./test/integration/polygon/aave/AaveV2TestWithWETH.ts --network localhost

      - name: AaveV3Test
        if: always()
        run: |
          npx hardhat test ./test/integration/polygon/aave/AaveV3Test.ts --network localhost

      - name: AaveV3TestWithWETH
        if: always()
        run: |
          npx hardhat test ./test/integration/polygon/aave/AaveV3TestWithWETH.ts --network localhost

      - name: AaveV2V3Test
        if: always()
        run: |
          npx hardhat test ./test/integration/polygon/aave/AaveV2V3Test.ts --network localhost

  polygon-integration4:
    name: PIT 4 - EasySwapper
    runs-on: ubuntu-latest
    needs: check_flags
    if: ${{ contains(needs.check_flags.outputs.message, '[run-integration]') || contains(needs.check_flags.outputs.message, '[run-polygon]') || contains(needs.check_flags.outputs.message, '[run-easy-swapper]')}}
    env:
      POLYGON_URL: ${{ secrets.POLYGON_ALCHEMY_URL_INTEGRATION_TEST }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Hit node_modules cache
        uses: actions/cache@v3
        id: node-cache
        with:
          path: "**/node_modules"
          key: npm-v2-${{ hashFiles('**/package-lock.json') }}
          restore-keys: npm-v2-
      - name: Install dependencies
        run: npm ci
        if: steps.node-cache.outputs.cache-hit != 'true'
      - name: Run Polygon fork in background
        run: |
          npx hardhat node --config hardhat.config-compile.ts --fork $POLYGON_URL &
      - name: Hardhat compile TypeChain
        run: npx hardhat --config hardhat.config-compile.ts typechain
      - name: Hardhat compile
        run: npx hardhat compile

      - name: DhedgeEasySwapperTest
        if: always()
        run: |
          npx hardhat test ./test/integration/polygon/DhedgeEasySwapperTest.ts --network localhost

      - name: EasySwapperGuardTest
        if: always()
        run: |
          npx hardhat test ./test/integration/polygon/EasySwapperGuardTest.ts --network localhost

  polygon-integration5:
    name: PIT 5 - Core contracts related
    runs-on: ubuntu-latest
    needs: check_flags
    if: ${{ contains(needs.check_flags.outputs.message, '[run-integration]') || contains(needs.check_flags.outputs.message, '[run-polygon]') }}
    env:
      POLYGON_URL: ${{ secrets.POLYGON_ALCHEMY_URL_INTEGRATION_TEST }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Hit node_modules cache
        uses: actions/cache@v3
        id: node-cache
        with:
          path: "**/node_modules"
          key: npm-v2-${{ hashFiles('**/package-lock.json') }}
          restore-keys: npm-v2-
      - name: Install dependencies
        run: npm ci
        if: steps.node-cache.outputs.cache-hit != 'true'
      - name: Run Polygon fork in background
        run: |
          npx hardhat node --config hardhat.config-compile.ts --fork $POLYGON_URL &
      - name: Hardhat compile TypeChain
        run: npx hardhat --config hardhat.config-compile.ts typechain
      - name: Hardhat compile
        run: npx hardhat compile

      - name: DhedgePoolAggregatorTest
        if: always()
        run: |
          npx hardhat test ./test/integration/polygon/DhedgePoolAggregatorTest.ts --network localhost

      - name: DhedgeSuperSwapperTest
        if: always()
        run: |
          npx hardhat test ./test/integration/polygon/DhedgeSuperSwapperTest.ts --network localhost

      - name: DhedgeUniV3V2RouterTest
        if: always()
        run: |
          npx hardhat test ./test/integration/polygon/DhedgeUniV3V2RouterTest.ts --network localhost

      - name: ExecTransactionsTest
        if: always()
        run: |
          npx hardhat test ./test/integration/polygon/ExecTransactionsTest.ts --network localhost

      - name: ETHCrossAggregatorTest
        if: always()
        run: |
          npx hardhat test ./test/integration/polygon/priceAggregators/ETHCrossAggregatorTest.ts --network localhost

      - name: MaticXPriceAggregatorTest
        if: always()
        run: |
          npx hardhat test ./test/integration/polygon/priceAggregators/MaticXPriceAggregatorTest.ts --network localhost

      - name: ManagerFeeTest
        if: always()
        run: |
          npx hardhat test ./test/integration/polygon/ManagerFeeTest.ts --network localhost

      - name: WithdrawToTest
        if: always()
        run: |
          npx hardhat test ./test/integration/polygon/WithdrawToTest.ts --network localhost
