name: Polygon IntegrationTest
on: [push]

jobs:
  polygon-integration1:
    if: "contains(join(github.event.commits.*.message), '[run-polygon]') || contains(join(github.event.commits.*.message), '[run-integration]') || contains(github.event.ref, 'master')"
    name: PIT 1
    runs-on: ubuntu-latest
    env:
      POLYGON_URL: ${{ secrets.POLYGON_ALCHEMY_URL_INTEGRATION_TEST }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Node module cache
        uses: actions/cache@v2
        id: node-cache
        with:
          path: "**/node_modules"
          key: npm-v2-${{ hashFiles('**/package-lock.json') }}
          restore-keys: npm-v2-
      - name: Install dependencies
        run: npm install
        if: steps.node-cache.outputs.cache-hit != 'true'

      - name: Run Polygon Fork in background
        run: |
          npx hardhat node --config hardhat.config-compile.ts --fork $POLYGON_URL &

      - name: Hardhat compile TypeChain
        run: npx hardhat --config hardhat.config-compile.ts typechain
        if: steps.typechain-cache.outputs.cache-hit != 'true'

      - name: Hardhat compile
        run: npx hardhat compile
        if: steps.hardhat-cache.outputs.cache-hit != 'true'

      # We run these separately because then it fails faster AND you can tell immediately whichtest failed via githu
      - name: BalancerTest
        if: always()
        run: |
          npx hardhat test ./test/integration/polygon/BalancerTest.ts --network localhost

      - name: Balancer V2 Staking (Asset Guard)
        if: always()
        run: |
          npx hardhat test ./test/integration/polygon/balancerV2/BalancerV2GaugeAssetGuardTest.ts --network localhost

      - name: Balancer V2 Staking (Contract Guard)
        if: always()
        run: |
          npx hardhat test ./test/integration/polygon/balancerV2/BalancerV2GaugeContractGuardTest.ts --network localhost

      - name: Balancer RewardsTest
        if: always()
        run: |
          npx hardhat test ./test/integration/polygon/BalancerRewardsTest.ts --network localhost

      - name: BalancerStablePoolAggregatorTest
        if: always()
        run: |
          npx hardhat test ./test/integration/polygon/BalancerStablePoolAggregatorTest.ts --network localhost

      - name: DHedgePoolAggregatorTest
        if: always()
        run: |
          npx hardhat test ./test/integration/polygon/DHedgePoolAggregatorTest.ts --network localhost

      - name: DHedgePoolPriceOracleTest
        if: always()
        run: |
          npx hardhat test ./test/integration/polygon/DHedgePoolPriceOracleTest.ts --network localhost

      - name: DhedgeSuperSwapperTest
        if: always()
        run: |
          npx hardhat test ./test/integration/polygon/DhedgeSuperSwapperTest.ts --network localhost

      - name: DhedgeSwapTest
        if: always()
        run: |
          npx hardhat test ./test/integration/polygon/DhedgeSwapTest.ts --network localhost

      - name: EarlyExitTest
        if: always()
        run: |
          npx hardhat test ./test/integration/polygon/EarlyExitTest.ts --network localhost

      - name: EasySwapperGuardTest
        if: always()
        run: |
          npx hardhat test ./test/integration/polygon/EasySwapperGuardTest.ts --network localhost

      - name: ETHCrossAggregatorTestTest
        if: always()
        run: |
          npx hardhat test ./test/integration/polygon/ETHCrossAggregatorTest.ts --network localhost

      - name: dQUICKPriceAggregatorTest
        if: always()
        run: |
          npx hardhat test ./test/integration/polygon/dQUICKPriceAggregatorTest.ts --network localhost

      - name: MaticXPriceAggregatorTest
        if: always()
        run: |
          npx hardhat test ./test/integration/polygon/MaticXPriceAggregatorTest.ts --network localhost

  # Polygontest are current split in 3 because they use more than 10k matic together... its also faster
  polygon-integration2:
    if: "contains(join(github.event.commits.*.message), '[run-polygon]') || contains(join(github.event.commits.*.message), '[run-integration]') || contains(github.event.ref, 'master')"
    name: PIT 2
    runs-on: ubuntu-latest
    env:
      POLYGON_URL: ${{ secrets.POLYGON_ALCHEMY_URL_INTEGRATION_TEST }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Node module cache
        uses: actions/cache@v2
        id: node-cache
        with:
          path: "**/node_modules"
          key: npm-v2-${{ hashFiles('**/package-lock.json') }}
          restore-keys: npm-v2-
      - name: Install dependencies
        run: npm install
        if: steps.node-cache.outputs.cache-hit != 'true'

      - name: Run Polygon Fork in background
        run: |
          npx hardhat node --config hardhat.config-compile.ts --fork $POLYGON_URL &

      - name: Hardhat compile TypeChain
        run: npx hardhat --config hardhat.config-compile.ts typechain
        if: steps.typechain-cache.outputs.cache-hit != 'true'

      - name: Hardhat compile
        run: npx hardhat compile
        if: steps.hardhat-cache.outputs.cache-hit != 'true'

      # We run these separately because then it fails faster AND you can tell immediately whichtest failed via github
      - name: LendingEnabledAssetGuardTest
        if: always()
        run: |
          npx hardhat test ./test/integration/polygon/LendingEnabledAssetGuardTest.ts --network localhost

      - name: OneInchTest
        if: always()
        run: |
          npx hardhat test ./test/integration/polygon/OneInchTest.ts --network localhost

      - name: QuickswapTest
        run: |
          npx hardhat test ./test/integration/polygon/QuickswapTest.ts --network localhost

      - name: SushiswapTest
        if: always()
        run: |
          npx hardhat test ./test/integration/polygon/SushiswapTest.ts --network localhost

      - name: ArrakisTest
        if: always()
        run: |
          npx hardhat test ./test/integration/polygon/arrakis/*.ts --network localhost

      - name: UniswapV3NonfungiblePositionGuardTest
        if: always()
        run: |
          npx hardhat test ./test/integration/polygon/UniswapV3NonfungiblePositionGuardTest.ts --network localhost

      - name: UniswapV3AssetGuardTest
        if: always()
        run: |
          npx hardhat test ./test/integration/polygon/UniswapV3AssetGuardTest.ts --network localhost

      - name: UniswapV3SwapRouterGuardTest
        if: always()
        run: |
          npx hardhat test ./test/integration/polygon/UniswapV3SwapRouterGuardTest.ts --network localhost

      - name: Manager Fees
        if: always()
        run: |
          npx hardhat test ./test/integration/polygon/ManagerFeeTest.ts --network localhost

      - name: WithdrawToTest
        if: always()
        run: |
          npx hardhat test ./test/integration/polygon/WithdrawToTest.ts --network localhost

  polygon-aave-tests:
    if: "contains(join(github.event.commits.*.message), '[run-polygon]') || contains(join(github.event.commits.*.message), '[run-integration]') || contains(github.event.ref, 'master')"
    name: PIT 3 - Aave Tests
    runs-on: ubuntu-latest
    env:
      POLYGON_URL: ${{ secrets.POLYGON_ALCHEMY_URL_INTEGRATION_TEST }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Node module cache
        uses: actions/cache@v2
        id: node-cache
        with:
          path: "**/node_modules"
          key: npm-v2-${{ hashFiles('**/package-lock.json') }}
          restore-keys: npm-v2-
      - name: Install dependencies
        run: npm install
        if: steps.node-cache.outputs.cache-hit != 'true'

      - name: Run Polygon Fork in background
        run: |
          npx hardhat node --config hardhat.config-compile.ts --fork $POLYGON_URL &

      - name: Hardhat compile TypeChain
        run: npx hardhat --config hardhat.config-compile.ts typechain
        if: steps.typechain-cache.outputs.cache-hit != 'true'

      - name: Hardhat compile
        run: npx hardhat compile
        if: steps.hardhat-cache.outputs.cache-hit != 'true'

      # We run these separately because then it fails faster AND you can tell immediately whichtest failed via github
      - name: AaveV2Test
        if: always()
        run: |
          npx hardhat test ./test/integration/polygon/AaveV2Test.ts --network localhost

      - name: AaveV2TestWithWETH
        if: always()
        run: |
          npx hardhat test ./test/integration/polygon/AaveV2TestWithWETH.ts --network localhost

      - name: AaveV3Test
        if: always()
        run: |
          npx hardhat test ./test/integration/polygon/AaveV3Test.ts --network localhost

      - name: AaveV3TestWithWETH
        if: always()
        run: |
          npx hardhat test ./test/integration/polygon/AaveV3TestWithWETH.ts --network localhost

      - name: AaveV2V3Test
        if: always()
        run: |
          npx hardhat test ./test/integration/polygon/AaveV2V3Test.ts --network localhost

  polygon-integration4:
    if: "contains(join(github.event.commits.*.message), '[run-easy-swapper]') || contains(join(github.event.commits.*.message), '[run-polygon]') || contains(join(github.event.commits.*.message), '[run-integration]') || contains(github.event.ref, 'master')"
    name: PIT 4
    runs-on: ubuntu-latest
    env:
      POLYGON_URL: ${{ secrets.POLYGON_ALCHEMY_URL_INTEGRATION_TEST }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Node module cache
        uses: actions/cache@v2
        id: node-cache
        with:
          path: "**/node_modules"
          key: npm-v2-${{ hashFiles('**/package-lock.json') }}
          restore-keys: npm-v2-
      - name: Install dependencies
        run: npm install
        if: steps.node-cache.outputs.cache-hit != 'true'

      - name: Run Polygon Fork in background
        run: |
          npx hardhat node --config hardhat.config-compile.ts --fork $POLYGON_URL &

      - name: Hardhat compile TypeChain
        run: npx hardhat --config hardhat.config-compile.ts typechain
        if: steps.typechain-cache.outputs.cache-hit != 'true'

      - name: Hardhat compile
        run: npx hardhat compile
        if: steps.hardhat-cache.outputs.cache-hit != 'true'

      - name: DhedgeEasySwapper
        if: always()
        run: |
          npx hardhat test ./test/integration/polygon/DhedgeEasySwapperTest.ts --network localhost

      - name: MedianTWAPAggregatorTest
        if: always()
        run: |
          npx hardhat test ./test/integration/polygon/MedianTWAPAggregatorTest.ts --network localhost
