name: Run Lint & Test

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize

jobs:
  checks:
    name: Linting & Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Hit node_modules cache
        uses: actions/cache@v3
        id: node-cache
        with:
          path: "**/node_modules"
          key: npm-v2-${{ hashFiles('**/package-lock.json') }}
          restore-keys: npm-v2-

      - name: Install dependencies
        run: npm ci
        if: steps.node-cache.outputs.cache-hit != 'true'

      - name: Hardhat compile TypeChain
        run: npx hardhat --config hardhat.config-compile.ts typechain

      - name: Hardhat compile
        run: npx hardhat compile

      - name: Run lint
        run: npm run lint

      - name: Run test
        run: npm run test:unit
